name: "mybbs"
mode: "release"
host: localhost
port: 8081
version: "v0.0.1"
snowflake:
  start_time: "2023-01-01"
  machine_id: 1

auth:
  jwt_expired:
  secret: "hello"

email:

log:
  model: "dev"
  level: "info"
  filename: "app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456
  database: "mybbs"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: localhost
  port: 6379
  password:
  database: 5
  pool_size: 100